export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const DOCUMENTS = "DOCUMENTS";
export const UPLOAD_DOCUMENT_MODAL = "UPLOAD_DOCUMENT_MODAL";

export const UPDATE_CURR_ROUTE = "UPDATE_CURR_ROUTE";